Vagrant::Config.run do |config|
  config.vm.box = "centos56_64-chef10"
  config.vm.boot_mode = :gui

  config.ssh.forwarded_port_key = "ssh"
  config.vm.forward_port("ssh", 22, 2222)

  config.vm.forward_port("http", 80, 8080)
  config.vm.customize do |vm|
    vm.memory_size = 1024
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = [ "cookbooks" ]
    chef.roles_path     = "roles"
    chef.data_bags_path = "data_bags"
    chef.add_role("trender")
  end

end
