Vagrant::Config.run do |config|

  config.vm.box = "centos56_64-chef10"
  config.vm.boot_mode = :gui

  config.vm.customize do |vm|
    vm.memory_size = 512
  end

  config.ssh.forwarded_port_key = "ssh"
  config.vm.forward_port("ssh", 22, 2222)
  config.vm.forward_port("catalyst", 3000, 3000)

  config.vm.provision :chef_solo do |chef|
    #chef.provisioning_path = "/srv/chef"
    chef.cookbooks_path = ["cookbooks"]
    chef.roles_path     = "roles"
    #chef.data_bags_path = "data_bags"
    chef.add_role("catalyst")
  end

end
